# Generated by Django 5.2 on 2025-05-02 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('layout_type', models.CharField(choices=[('GRID', 'Grid'), ('HORIZONTAL', 'Horizontal')], max_length=10)),
                ('banners', models.ManyToManyField(blank=True, related_name='home_items', to='dashboard.homebanner')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRODUCT', 'Product'), ('SUBCATEGORY', 'Subcategory'), ('GENERIC', 'Generic')], max_length=50)),
                ('generic_text', models.CharField(blank=True, max_length=255)),
                ('generic_image_url', models.URLField(blank=True)),
                ('home_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='dashboard.homeitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.subcategory')),
            ],
        ),
    ]
